# Generated by Django 4.1.12 on 2023-12-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailUser',
        ),
    ]
