# Generated by Django 4.1.12 on 2023-12-01 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('disponibilidade', models.BooleanField(default=False, verbose_name='disponível')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cursomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', multiselectfield.db.fields.MultiSelectField(choices=[('1', '1º horário (7:35 - 8:25)'), ('2', '2º horário (8:25 - 9:10)'), ('3', '3º horário (9:30 - 10:20)'), ('4', '4º horário (10:20 - 11:10)'), ('5', '5º horário (11:10 - 12:00)'), ('6', '6º horário (13:30 - 14:20)'), ('7', '7º horário (14:20 - 15:05'), ('8', '8º horário (15:20 - 16:10)'), ('9', '9º horário (16:10 - 17:00)')], max_length=50)),
                ('concluida', models.BooleanField(default=False, verbose_name='Entregue')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.cursomodel')),
                ('projetor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.projetormodel')),
                ('turmas', models.ManyToManyField(to='reservas.turmamodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
