# Generated by Django 4.1.12 on 2023-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservamodel',
            name='concluida',
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='devolucao',
            field=models.BooleanField(default=False, verbose_name='Projetor Devolvido'),
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='entregue',
            field=models.BooleanField(default=False, verbose_name='Projetor Entregue'),
        ),
    ]
